import { 
  Match, 
  Transaction, 
  User, 
  LeaderboardPlayer,
  PaymentSettings,
  DepositRequest,
  WithdrawRequest,
  ResultSubmission
} from '../types';

export const initialUser: User = {
  id: 'user_01',
  name: 'Sirajul Hoque',
  phone: '01832822322',
  password: 'Agriments@09',
  isAdmin: true,
  ludoKingName: 'Sirajul Hoque',
  gamingBalance: 0.00,
  winningBalance: 0.00,
  matchesPlayed: 0,
  totalWinnings: 0.00,
  referralCode: 'LX5892',
  joinedAt: 'Today',
};

export const initialMatches: Match[] = [
  {
    id: 'm_259943',
    matchNo: '259943',
    title: '🔥 SPECIAL MATCH 🔥',
    subtitle: '২ জন জয়েন হলেই স্টার্ট দেওয়া হবে।',
    category: 'special',
    totalPrize: 400,
    entryFee: 220,
    version: 'Mobile',
    boardType: 'Ludo King',
    totalSeats: 2,
    joinedSeats: 1,
    joinedPlayers: [
      { name: 'Tanvir Ahmed', ludoKingName: 'Tanvir_Boss', joinedAt: '12:15 PM' }
    ],
    status: 'open',
    roomCode: '',
    isHot: true,
  },
  {
    id: 'm_259944',
    matchNo: '259944',
    title: '🔥 SPECIAL MATCH 🔥',
    subtitle: '২ জন জয়েন হলেই স্টার্ট দেওয়া হবে।',
    category: 'special',
    totalPrize: 4000,
    entryFee: 2150,
    version: 'Mobile',
    boardType: 'Ludo King',
    totalSeats: 2,
    joinedSeats: 2,
    joinedPlayers: [
      { name: 'Rahim Sheikh', ludoKingName: 'Rahim_King', joinedAt: '11:45 AM' },
      { name: 'Arif Hasan', ludoKingName: 'Arif_Pro', joinedAt: '11:50 AM' }
    ],
    status: 'full',
    roomCode: '',
    isHot: true,
  },
  {
    id: 'm_259945',
    matchNo: '259945',
    title: '🔥 SPECIAL MATCH 🔥',
    subtitle: '২ জন জয়েন হলেই স্টার্ট দেওয়া হবে।',
    category: 'special',
    totalPrize: 3000,
    entryFee: 1600,
    version: 'Mobile',
    boardType: 'Ludo King',
    totalSeats: 2,
    joinedSeats: 2,
    joinedPlayers: [
      { name: 'Kamal Hossain', ludoKingName: 'Kamal99', joinedAt: '10:30 AM' },
      { name: 'Shakil Khan', ludoKingName: 'Shakil_Ludo', joinedAt: '10:35 AM' }
    ],
    status: 'full',
    roomCode: '',
  },
  {
    id: 'm_259946',
    matchNo: '259946',
    title: '🔥 SPECIAL MATCH 🔥',
    subtitle: '২ জন জয়েন হলেই স্টার্ট দেওয়া হবে।',
    category: 'special',
    totalPrize: 2000,
    entryFee: 1100,
    version: 'Mobile',
    boardType: 'Ludo King',
    totalSeats: 2,
    joinedSeats: 2,
    joinedPlayers: [
      { name: 'Mahmudul Hasan', ludoKingName: 'Mahmud_BD', joinedAt: '09:15 AM' },
      { name: 'Sojib Mia', ludoKingName: 'SojibKing', joinedAt: '09:20 AM' }
    ],
    status: 'full',
    roomCode: '',
  },
  {
    id: 'm_259947',
    matchNo: '259947',
    title: '🔥 SPECIAL MATCH 🔥',
    subtitle: '২ জন জয়েন হলেই স্টার্ট দেওয়া হবে।',
    category: 'special',
    totalPrize: 1000,
    entryFee: 550,
    version: 'Mobile',
    boardType: 'Ludo King',
    totalSeats: 2,
    joinedSeats: 2,
    joinedPlayers: [
      { name: 'Rakib Islam', ludoKingName: 'Rakib_Fast', joinedAt: '12:00 PM' },
      { name: 'Nayeem', ludoKingName: 'Nayeem_King', joinedAt: '12:05 PM' }
    ],
    status: 'full',
    roomCode: '',
  },
  {
    id: 'm_259948',
    matchNo: '259948',
    title: '🔥 SPECIAL MATCH 🔥',
    subtitle: '২ জন জয়েন হলেই স্টার্ট দেওয়া হবে।',
    category: 'special',
    totalPrize: 600,
    entryFee: 330,
    version: 'Mobile',
    boardType: 'Ludo King',
    totalSeats: 2,
    joinedSeats: 2,
    joinedPlayers: [
      { name: 'Fahim', ludoKingName: 'Fahim_07', joinedAt: '11:10 AM' },
      { name: 'Hasan', ludoKingName: 'Hasan_Win', joinedAt: '11:12 AM' }
    ],
    status: 'full',
    roomCode: '',
  },
  {
    id: 'm_259949',
    matchNo: '259949',
    title: '🔥 SPECIAL MATCH 🔥',
    subtitle: '২ জন জয়েন হলেই স্টার্ট দেওয়া হবে।',
    category: 'special',
    totalPrize: 500,
    entryFee: 270,
    version: 'Mobile',
    boardType: 'Ludo King',
    totalSeats: 2,
    joinedSeats: 2,
    joinedPlayers: [
      { name: 'Rubel', ludoKingName: 'Rubel_BD', joinedAt: '10:00 AM' },
      { name: 'Shamim', ludoKingName: 'Shamim_Ludo', joinedAt: '10:05 AM' }
    ],
    status: 'full',
    roomCode: '',
  },
  {
    id: 'm_259950',
    matchNo: '259950',
    title: '🔥 SPECIAL MATCH 🔥',
    subtitle: '২ জন জয়েন হলেই স্টার্ট দেওয়া হবে।',
    category: 'special',
    totalPrize: 10000,
    entryFee: 5500,
    version: 'Mobile',
    boardType: 'Ludo King',
    totalSeats: 2,
    joinedSeats: 0,
    joinedPlayers: [],
    status: 'open',
    roomCode: '',
  },
  {
    id: 'm_259951',
    matchNo: '259951',
    title: '🔥 SPECIAL MATCH 🔥',
    subtitle: '২ জন জয়েন হলেই স্টার্ট দেওয়া হবে।',
    category: 'special',
    totalPrize: 740,
    entryFee: 400,
    version: 'Mobile',
    boardType: 'Ludo King',
    totalSeats: 2,
    joinedSeats: 1,
    joinedPlayers: [
      { name: 'Anisur Rahman', ludoKingName: 'Anis_Player', joinedAt: '12:10 PM' }
    ],
    status: 'open',
    roomCode: '',
  },
  {
    id: 'm_259952',
    matchNo: '259952',
    title: '🔥 SPECIAL MATCH 🔥',
    subtitle: '২ জন জয়েন হলেই স্টার্ট দেওয়া হবে।',
    category: 'special',
    totalPrize: 130,
    entryFee: 75,
    version: 'Mobile',
    boardType: 'Ludo King',
    totalSeats: 2,
    joinedSeats: 2,
    joinedPlayers: [
      { name: 'Rasel', ludoKingName: 'Rasel_King', joinedAt: '12:12 PM' },
      { name: 'Alamin', ludoKingName: 'Alamin_99', joinedAt: '12:14 PM' }
    ],
    status: 'full',
    roomCode: '',
  },
  {
    id: 'm_259953',
    matchNo: '259953',
    title: '🔥 SPECIAL MATCH 🔥',
    subtitle: '২ জন জয়েন হলেই স্টার্ট দেওয়া হবে।',
    category: 'special',
    totalPrize: 100,
    entryFee: 60,
    version: 'Mobile',
    boardType: 'Ludo King',
    totalSeats: 2,
    joinedSeats: 2,
    joinedPlayers: [
      { name: 'Biplob', ludoKingName: 'Biplob_Pro', joinedAt: '12:15 PM' },
      { name: 'Joynal', ludoKingName: 'Joynal_BD', joinedAt: '12:16 PM' }
    ],
    status: 'full',
    roomCode: '',
  },
  {
    id: 'm_259954',
    matchNo: '259954',
    title: '🔥 SPECIAL MATCH 🔥',
    subtitle: '২ জন জয়েন হলেই স্টার্ট দেওয়া হবে।',
    category: 'special',
    totalPrize: 90,
    entryFee: 50,
    version: 'Mobile',
    boardType: 'Ludo King',
    totalSeats: 2,
    joinedSeats: 2,
    joinedPlayers: [
      { name: 'Monir', ludoKingName: 'Monir_01', joinedAt: '12:18 PM' },
      { name: 'Zakir', ludoKingName: 'Zakir_Win', joinedAt: '12:19 PM' }
    ],
    status: 'full',
    roomCode: '',
  },
  {
    id: 'm_259955',
    matchNo: '259955',
    title: '🔥 SPECIAL MATCH 🔥',
    subtitle: '২ জন জয়েন হলেই স্টার্ট দেওয়া হবে।',
    category: 'special',
    totalPrize: 50,
    entryFee: 30,
    version: 'Mobile',
    boardType: 'Ludo King',
    totalSeats: 2,
    joinedSeats: 1,
    joinedPlayers: [
      { name: 'Shohel', ludoKingName: 'Shohel_BD', joinedAt: '12:20 PM' }
    ],
    status: 'open',
    roomCode: '',
  },
  // Time Matches
  {
    id: 'm_258530',
    matchNo: '258530',
    title: 'LUDO KING || 1 VS 1 || 258530',
    subtitle: '2026-08-30 08:10 PM',
    category: 'time',
    totalPrize: 30,
    entryFee: 20,
    version: 'Mobile',
    boardType: 'Ludo King',
    totalSeats: 2,
    joinedSeats: 2,
    joinedPlayers: [
      { name: 'Robin', ludoKingName: 'Robin_Ludo', joinedAt: '08:00 PM' },
      { name: 'Emon', ludoKingName: 'Emon_Boss', joinedAt: '08:05 PM' }
    ],
    status: 'full',
    roomCode: '',
    matchTime: '08:10 PM',
  },
  {
    id: 'm_258579',
    matchNo: '258579',
    title: 'LUDO KING || 1 VS 1 || 258579',
    subtitle: '2026-08-30 09:30 PM',
    category: 'time',
    totalPrize: 60,
    entryFee: 35,
    version: 'Mobile',
    boardType: 'Ludo King',
    totalSeats: 2,
    joinedSeats: 1,
    joinedPlayers: [
      { name: 'Kawsar', ludoKingName: 'Kawsar_BD', joinedAt: '09:00 PM' }
    ],
    status: 'open',
    roomCode: '',
    matchTime: '09:30 PM',
  }
];

export const initialTransactions: Transaction[] = [];

export const topPlayers: LeaderboardPlayer[] = [
  { rank: 1, name: 'Sabbir Hossain', matchesWon: 142, totalEarnings: 28450 },
  { rank: 2, name: 'Tanvir King', matchesWon: 119, totalEarnings: 22600 },
  { rank: 3, name: 'Arif Pro BD', matchesWon: 98, totalEarnings: 18400 },
  { rank: 4, name: 'Sirajul Hoque', matchesWon: 15, totalEarnings: 560 },
  { rank: 5, name: 'Kamal Gamer', matchesWon: 76, totalEarnings: 13900 },
  { rank: 6, name: 'Rubel Champion', matchesWon: 65, totalEarnings: 11200 },
  { rank: 7, name: 'Nayeem Master', matchesWon: 54, totalEarnings: 9500 },
  { rank: 8, name: 'Fahim Strike', matchesWon: 48, totalEarnings: 8200 },
];

export const initialPaymentSettings: PaymentSettings = {
  bkash: '01972943649',
  nagad: '01832822322',
  rocket: '01712345678',
  upay: '01972943649',
  whatsappSupport: '01972943649',
  telegramLink: 'https://t.me/skillzgame_official',
  marqueeNotice: '🔥 Skillzgame এ আপনাকে স্বাগতম! ২৪ ঘণ্টা ইনস্ট্যান্ট ডিপোজিট ও উইথড্রয়াল সুবিধা। হেল্পলাইন WhatsApp: 01972943649',
  popupNoticeTitle: 'Skillzgame নোটিশ 📢',
  popupNoticeText: 'Skillzgame এ আপনার দক্ষতায় ১v১ Block Puzzle Duel গেম খেলুন ও রিয়েল ক্যাশ প্রাইজ জিতুন। যেকোনো প্রয়োজনে ২৪/৭ কাস্টমার সাপোর্টে মেসেজ দিন।',
};

export const initialRegisteredUsers: User[] = [
  {
    id: 'user_01',
    name: 'Sirajul Hoque',
    phone: '01832822322',
    password: 'Agriments@09',
    isAdmin: true,
    ludoKingName: 'Sirajul Hoque',
    gamingBalance: 0.00,
    winningBalance: 0.00,
    matchesPlayed: 0,
    totalWinnings: 0.00,
    referralCode: 'LX5892',
    joinedAt: 'Aug 15, 2026',
    isBanned: false,
  },
  {
    id: 'user_02',
    name: 'Tanvir Ahmed',
    phone: '01711223344',
    password: '123456',
    isAdmin: false,
    ludoKingName: 'Tanvir_Boss',
    gamingBalance: 320.00,
    winningBalance: 400.00,
    matchesPlayed: 24,
    totalWinnings: 2400.00,
    referralCode: 'LX1002',
    joinedAt: 'Aug 18, 2026',
    isBanned: false,
  },
  {
    id: 'user_03',
    name: 'Rahim Sheikh',
    phone: '01988776655',
    password: '123456',
    isAdmin: false,
    ludoKingName: 'Rahim_King',
    gamingBalance: 150.00,
    winningBalance: 1200.00,
    matchesPlayed: 32,
    totalWinnings: 4100.00,
    referralCode: 'LX3341',
    joinedAt: 'Aug 10, 2026',
    isBanned: false,
  },
  {
    id: 'user_04',
    name: 'Arif Hasan',
    phone: '01655443322',
    password: '123456',
    isAdmin: false,
    ludoKingName: 'Arif_Pro',
    gamingBalance: 20.00,
    winningBalance: 650.00,
    matchesPlayed: 19,
    totalWinnings: 1800.00,
    referralCode: 'LX9912',
    joinedAt: 'Aug 21, 2026',
    isBanned: false,
  }
];

export const initialDepositRequests: DepositRequest[] = [
  {
    id: 'dep_101',
    userId: 'user_01',
    userName: 'Sirajul Hoque',
    userPhone: '01832822322',
    method: 'bKash',
    amount: 100,
    senderNumber: '01832822322',
    trxId: 'DHQ8SR8VEA',
    timestamp: 'আজ ১২:৩০ PM',
    status: 'PENDING',
  },
  {
    id: 'dep_102',
    userId: 'user_02',
    userName: 'Tanvir Ahmed',
    userPhone: '01711223344',
    method: 'Nagad',
    amount: 250,
    senderNumber: '01711223344',
    trxId: '9G7K21MN',
    timestamp: 'আজ ১১:১৫ AM',
    status: 'APPROVED',
  }
];

export const initialWithdrawRequests: WithdrawRequest[] = [
  {
    id: 'wth_201',
    userId: 'user_03',
    userName: 'Rahim Sheikh',
    userPhone: '01988776655',
    method: 'bKash',
    accountType: 'Personal',
    accountNumber: '01988776655',
    amount: 300,
    timestamp: 'আজ ১২:৪৫ PM',
    status: 'PENDING',
  }
];

export const initialResultSubmissions: ResultSubmission[] = [
  {
    id: 'res_301',
    userId: 'user_01',
    userName: 'Sirajul Hoque',
    userPhone: '01832822322',
    ludoKingName: 'Sirajul Hoque',
    matchId: 'm_259943',
    matchNo: '259943',
    roomCode: '06447612',
    prizeAmount: 400,
    status: 'PENDING',
    submittedAt: 'আজ ১২:৫০ PM',
    imageUrl: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=600&auto=format&fit=crop&q=80',
  }
];

export const paymentAccounts = {
  bkash: '01972943649',
  nagad: '01832822322',
  rocket: '01712345678',
  upay: '01972943649',
  whatsappSupport: '01972943649',
  telegramLink: 'https://t.me/lxludo_official',
};
